### ISSUE TITLE
DkimSigner went async but did not call Resume on the new thread, while handling event OnCategorizedMessage 

### ISSUE THREAD

**Issue by GhostScript-** [Pro/dkim-exchange#215]
### Versions

- **Windows Server Version**: Windows Server 2008 R2 Ent
- **Exchange Version**: 15.0.1365.1 (Exchange 2013 CU19)
- **Installed DKIM Exchange Version**: 3.0.13

### Description
(eventlog message)
error: 1057 - MSExchange Extensibility: Agent Exchange DkimSigner went async but did not call Resume on the new thread, while handling event OnCategorizedMessage 

### Steps to Reproduce
Seems to occur erratically, sometimes three times in same hour and sometimes once over the course of several hours.  

I had read about this in earlier versions and thought it had been fixed.

**Comment by jassonmc** [comment]
We are seeing exactly the same issue.
Only difference is we are on Windows Server 2012 Dtc.

**Comment by Pro** [comment]
That's fixed in #208 (but not yet included in a release)

**Comment by blub96** [comment]
Will there be a a relese with that fix?
We still face this Problem.

**Comment by varzdar** [comment]
We are seeing exactly the same issue on Exchange server 2019 CU13 with dkimsigner version 3.4 (2023-06-14)

**Comment by gesture1968** [comment]
Any updates on a fix? We're experiencing the same issue

**Comment by nepgituser** [comment]
Experiencing this issue as well.

**Comment by jnorell** [comment]
We're seeing this with 3.4.2 (the latest release?).

**Comment by shumaid** [comment]
Noted on Win 2012 R2 running Exchange 2016 CU23  15.1.2507.6  Singer ver 3.4.0
Still can not get DKIM to work !!!

**Comment by jjvalstar** [comment]
I have the same but I do run on a Window Server 2016 with the latest update installed.
The Exchange Server 2016 runs on CU23 with all updates which are available are done.

Dkim-Signer version Version 3.4.0
Exchange Server Version : 15.1.2507.17

Beside that I had another issue as well. My server handles two domain wherefor I created a DKIM for which works perfectly. I wanted to add another DKIM for 1 domain (so, it would be the second for that domain) but then the MSExchangeTransport stops and trying to restart without success. If I deleted that second DKIM entry for that domain the service startsup again.
