### ISSUE TITLE
Agent went async Error

### ISSUE THREAD

**Issue by theklap** [Pro/dkim-exchange#362]
### Versions

- **Windows Server Version**: Server 2019 (Build 17763.2803)
- **Exchange Version**: 2019 15.02.1118.007
- **Installed DKIM Exchange Version**: 3.4.0

### Description

Receive an error in the windows application Log.  
Source : MSExchange Extensibility
Agent 'Exchange DKIMSigner' went async but did not call Resume on the new thread, while handling event 'OnCategorizedMessage'

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by DJBenson** [comment]
Can you provide the full path in Event Viewer for this issue? Or a screenshot?

**Comment by DJBenson** [comment]
I wonder if it's similar to [this](https://support.eset.com/en/kb6540-error-message-event-id-1057-agent-eset-filtering-av-agent-went-async-but-did-not-call-resume-on-the-new-thread-while-handling-event-onsubmittedmessage) issue which Eset say is safe to ignore.

**Comment by theklap** [comment]
Screenshot of event.


![Screenshot 2022-05-23 090316](https://user-images.githubusercontent.com/3182305/169837501-d57f8599-2a5a-46b7-93f3-64369777c703.jpg)

**Comment by donald2612** [comment]
Can confirm the same on my exc2019 cu12 - though I cannot complain about something that does not work like it should ;)

**Comment by tonyfuenca** [comment]
I can confirm this issue at EXC-2016-CU23-May22SU and it wasn't present before CU23. No final user have sent any issue regarding this.

**Comment by DJBenson** [comment]
This issue is fixed by v3.4.1. This is currently flagged as pre-release but I've installed it in my production environment and not seen any instances of this error since. If you want to try this before the pre-release flag is removed, check the "Include prerelease versions" in the UI.

This turned out to be a regression of #215.

**Comment by YevgeniyN** [comment]
Hi.

I'm getting error after upgrade to 3.4.1 (by the way, it still shows 3.4.0 in DKIM Signer version info)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileLoadException: Could not load file or assembly 'BouncyCastle.Crypto, Version=1.9.0.0, Culture=neutral, PublicKeyToken=0e99375e54769942' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'BouncyCastle.Crypto, Version=1.9.0.0, Culture=neutral, PublicKeyToken=0e99375e54769942'
   at Configuration.DkimSigner.MainWindow.GenerateKey(String fileName)
   at Configuration.DkimSigner.MainWindow.btDomainKeyGenerate_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].



************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4430.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Configuration.DkimSigner
    Assembly Version: 3.4.0.0
    Win32 Version: 3.4.0.0
    CodeBase: file:///C:/Program%20Files/Exchange%20DkimSigner/Configuration.DkimSigner.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4410.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4380.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4261.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Management.Automation
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.14393.2248
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management.Automation/v4.0_3.0.0.0__31bf3856ad364e35/System.Management.Automation.dll
----------------------------------------
System.ServiceProcess
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceProcess/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ServiceProcess.dll
----------------------------------------
Microsoft.PowerShell.Commands.Diagnostics
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.14393.2125
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Diagnostics/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Diagnostics.dll
----------------------------------------
System.Configuration.Install
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration.Install/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.Install.dll
----------------------------------------
Microsoft.PowerShell.ConsoleHost
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.14393.2248
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.ConsoleHost/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.ConsoleHost.dll
----------------------------------------
Microsoft.PowerShell.Commands.Utility
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.14393.2156
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Utility/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Utility.dll
----------------------------------------
Microsoft.PowerShell.Commands.Management
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.14393.2189
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Management/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Management.dll
----------------------------------------
Microsoft.Management.Infrastructure
    Assembly Version: 1.0.0.0
    Win32 Version: 10.0.14393.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Management.Infrastructure/v4.0_1.0.0.0__31bf3856ad364e35/Microsoft.Management.Infrastructure.dll
----------------------------------------
Microsoft.PowerShell.Security
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.14393.2155
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Security/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Security.dll
----------------------------------------
Microsoft.WSMan.Management
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.14393.2189
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.WSMan.Management/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.WSMan.Management.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4290.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.DirectoryServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.DirectoryServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.DirectoryServices.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4430.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
Microsoft.Exchange.PowerShell.Configuration
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.PowerShell.Configuration.dll
----------------------------------------
Microsoft.Exchange.Data.Directory
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.Directory.DLL
----------------------------------------
Microsoft.Exchange.Diagnostics
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Diagnostics.DLL
----------------------------------------
Microsoft.Exchange.Data
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.DLL
----------------------------------------
Microsoft.Exchange.Net
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Net.DLL
----------------------------------------
Microsoft.Exchange.Common
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Common.DLL
----------------------------------------
Microsoft.Exchange.Data.Common
    Assembly Version: 15.1.2503.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Exchange.Data.Common/v4.0_15.1.2503.0__31bf3856ad364e35/Microsoft.Exchange.Data.Common.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4261.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4261.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4330.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Microsoft.Exchange.Management.Transport
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.Transport.DLL
----------------------------------------
Microsoft.Exchange.Configuration.ObjectModel
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Configuration.ObjectModel.DLL
----------------------------------------
Microsoft.Exchange.Management.Recipient
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.Recipient.DLL
----------------------------------------
Microsoft.Exchange.Management
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.DLL
----------------------------------------
Microsoft.Exchange.Data.Transport
    Assembly Version: 15.1.2503.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Exchange.Data.Transport/v4.0_15.1.2503.0__31bf3856ad364e35/Microsoft.Exchange.Data.Transport.dll
----------------------------------------
Microsoft.Exchange.Transport.Logging.Search
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Transport.Logging.Search.DLL
----------------------------------------
Microsoft.Exchange.Management.Powershell.Support
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.Powershell.Support.DLL
----------------------------------------
Microsoft.Exchange.Rules.Common
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Rules.Common.DLL
----------------------------------------
Microsoft.Exchange.MessagingPolicies.Rules
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.MessagingPolicies.Rules.DLL
----------------------------------------
Microsoft.Exchange.Transport.Agent.InterceptorAgent
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Transport.Agent.InterceptorAgent.DLL
----------------------------------------
Microsoft.Exchange.Transport.Agent.AntiSpam.Common
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Transport.Agent.AntiSpam.Common.DLL
----------------------------------------
Microsoft.Exchange.Management.Provisioning
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.Provisioning.DLL
----------------------------------------
Microsoft.Exchange.MessageSecurity
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.MessageSecurity.DLL
----------------------------------------
Microsoft.Exchange.StoreProvider
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.StoreProvider.DLL
----------------------------------------
Microsoft.Exchange.Management.Mobility
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.Mobility.DLL
----------------------------------------
Microsoft.Exchange.Data.Storage
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.Storage.DLL
----------------------------------------
Microsoft.Exchange.Management.Migration
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.Migration.DLL
----------------------------------------
Microsoft.Exchange.MailboxReplicationService.Common
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.MailboxReplicationService.Common.DLL
----------------------------------------
Microsoft.Exchange.Migration
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Migration.DLL
----------------------------------------
Microsoft.Exchange.Data.MailboxLoadBalance
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.MailboxLoadBalance.DLL
----------------------------------------
Microsoft.Exchange.Data.Mapi
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.Mapi.DLL
----------------------------------------
Microsoft.Exchange.Compliance.TaskDistributionCommon
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Compliance.TaskDistributionCommon.DLL
----------------------------------------
Microsoft.Exchange.Data.ApplicationLogic
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.ApplicationLogic.DLL
----------------------------------------
Microsoft.Office.CompliancePolicy.Platform
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Office.CompliancePolicy.Platform.DLL
----------------------------------------
Microsoft.Exchange.Data.StoreObjects
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.StoreObjects.DLL
----------------------------------------
Microsoft.Exchange.UM.UMCommon
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.UM.UMCommon.DLL
----------------------------------------
Microsoft.Exchange.Transport.Sync.Common
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Transport.Sync.Common.DLL
----------------------------------------
Microsoft.Exchange.Data.Providers
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.Providers.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.Exchange.PswsClient
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.PswsClient.DLL
----------------------------------------
Microsoft.Exchange.Management.CompliancePolicy
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.CompliancePolicy.DLL
----------------------------------------
Microsoft.Exchange.Data.resources
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/uk/Microsoft.Exchange.Data.resources.DLL
----------------------------------------
Microsoft.Exchange.Common.Directory.DirectoryVariantConfig
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Common.Directory.DirectoryVariantConfig.DLL
----------------------------------------
Microsoft.Exchange.Data.Directory.resources
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/en/Microsoft.Exchange.Data.Directory.resources.DLL
----------------------------------------
Microsoft.Exchange.Configuration.RedirectionModule
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Configuration.RedirectionModule.DLL
----------------------------------------
Microsoft.Exchange.WorkloadManagement
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.WorkloadManagement.DLL
----------------------------------------
Microsoft.Exchange.Sqm
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Sqm.DLL
----------------------------------------
Microsoft.Exchange.Configuration.Core
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Configuration.Core.DLL
----------------------------------------
Microsoft.Exchange.VariantConfiguration.ExCore
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.VariantConfiguration.ExCore.DLL
----------------------------------------
Microsoft.Exchange.VariantConfiguration.Core
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.VariantConfiguration.Core.DLL
----------------------------------------
Microsoft.Search.Platform.Parallax
    Assembly Version: 3.3.0.0
    Win32 Version: 3.3.4.0
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Search.Platform.Parallax.DLL
----------------------------------------
Microsoft.Exchange.VariantConfiguration
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.VariantConfiguration.dll
----------------------------------------
Google.Protobuf
    Assembly Version: 3.7.0.0
    Win32 Version: 3.7.0.0
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Google.Protobuf.DLL
----------------------------------------
Microsoft.PowerShell.HostingTools
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.PowerShell.HostingTools.DLL
----------------------------------------
Microsoft.Exchange.Configuration.ObjectModel.resources
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/en/Microsoft.Exchange.Configuration.ObjectModel.resources.DLL
----------------------------------------
System.Runtime.Caching
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Caching/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Caching.dll
----------------------------------------
Microsoft.Exchange.Extensibility.Internal
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Extensibility.Internal.DLL
----------------------------------------
Microsoft.Exchange.Transport.Flighting
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/Bin/Microsoft.Exchange.Transport.Flighting.dll
----------------------------------------
Microsoft.Exchange.Common.ComponentConfig.Transport
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/Bin/Microsoft.Exchange.Common.ComponentConfig.Transport.DLL
----------------------------------------
Microsoft.Exchange.Core.TimeZone
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Core.TimeZone.DLL
----------------------------------------
Microsoft.Exchange.Compliance
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Compliance.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.Exchange.Core.TimeZone.resources
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/en/Microsoft.Exchange.Core.TimeZone.resources.DLL
----------------------------------------
System.DirectoryServices.Protocols
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.DirectoryServices.Protocols/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.DirectoryServices.Protocols.dll
----------------------------------------
Microsoft.Exchange.VariantConfiguration.GlobalSettings
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.VariantConfiguration.GlobalSettings.DLL
----------------------------------------
Microsoft.Exchange.Data.resources
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/en/Microsoft.Exchange.Data.resources.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.Exchange.Transport.Extensibility
    Assembly Version: 15.0.0.0
    Win32 Version: 15.01.2507.006
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Transport.Extensibility.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by YevgeniyN** [comment]
Sorry, I've forgot to add version - Exchange 2016 CU23 here

**Comment by DJBenson** [comment]
> Hi.
> 
> I'm getting error after upgrade to 3.4.1 (by the way, it still shows 3.4.0 in DKIM Signer version info)
> 
> See the end of this message for details on invoking just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text ************** System.IO.FileLoadException: Could not load file or assembly 'BouncyCastle.Crypto, Version=1.9.0.0, Culture=neutral, PublicKeyToken=0e99375e54769942' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) File name: 'BouncyCastle.Crypto, Version=1.9.0.0, Culture=neutral, PublicKeyToken=0e99375e54769942' at Configuration.DkimSigner.MainWindow.GenerateKey(String fileName) at Configuration.DkimSigner.MainWindow.btDomainKeyGenerate_Click(Object sender, EventArgs e) at System.Windows.Forms.Control.OnClick(EventArgs e) at System.Windows.Forms.Button.OnClick(EventArgs e) at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent) at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks) at System.Windows.Forms.Control.WndProc(Message& m) at System.Windows.Forms.ButtonBase.WndProc(Message& m) at System.Windows.Forms.Button.WndProc(Message& m) at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
> 
> ## ************** Loaded Assemblies **************
> mscorlib
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4430.0 built by: NET48REL1LAST_B
> CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
> ## Configuration.DkimSigner
> Assembly Version: 3.4.0.0
> Win32 Version: 3.4.0.0
> CodeBase: file:///C:/Program%20Files/Exchange%20DkimSigner/Configuration.DkimSigner.exe
> ## System.Windows.Forms
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4410.0 built by: NET48REL1LAST_B
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ## System
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4380.0 built by: NET48REL1LAST_B
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ## System.Drawing
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ## System.Configuration
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ## System.Core
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ## System.Xml
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.3761.0 built by: NET48REL1
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ## System.Runtime.Serialization
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4261.0 built by: NET48REL1LAST_B
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
> ## System.Management.Automation
> Assembly Version: 3.0.0.0
> Win32 Version: 10.0.14393.2248
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management.Automation/v4.0_3.0.0.0__31bf3856ad364e35/System.Management.Automation.dll
> ## System.ServiceProcess
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.3761.0 built by: NET48REL1
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceProcess/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ServiceProcess.dll
> ## Microsoft.PowerShell.Commands.Diagnostics
> Assembly Version: 3.0.0.0
> Win32 Version: 10.0.14393.2125
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Diagnostics/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Diagnostics.dll
> ## System.Configuration.Install
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.3761.0 built by: NET48REL1
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration.Install/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.Install.dll
> ## Microsoft.PowerShell.ConsoleHost
> Assembly Version: 3.0.0.0
> Win32 Version: 10.0.14393.2248
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.ConsoleHost/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.ConsoleHost.dll
> ## Microsoft.PowerShell.Commands.Utility
> Assembly Version: 3.0.0.0
> Win32 Version: 10.0.14393.2156
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Utility/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Utility.dll
> ## Microsoft.PowerShell.Commands.Management
> Assembly Version: 3.0.0.0
> Win32 Version: 10.0.14393.2189
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Management/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Management.dll
> ## Microsoft.Management.Infrastructure
> Assembly Version: 1.0.0.0
> Win32 Version: 10.0.14393.0
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Management.Infrastructure/v4.0_1.0.0.0__31bf3856ad364e35/Microsoft.Management.Infrastructure.dll
> ## Microsoft.PowerShell.Security
> Assembly Version: 3.0.0.0
> Win32 Version: 10.0.14393.2155
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Security/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Security.dll
> ## Microsoft.WSMan.Management
> Assembly Version: 3.0.0.0
> Win32 Version: 10.0.14393.2189
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.WSMan.Management/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.WSMan.Management.dll
> ## System.Data
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4290.0 built by: NET48REL1LAST_B
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
> ## System.Management
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.3761.0 built by: NET48REL1
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
> ## System.DirectoryServices
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.3761.0 built by: NET48REL1
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.DirectoryServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.DirectoryServices.dll
> ## Anonymously Hosted DynamicMethods Assembly
> Assembly Version: 0.0.0.0
> Win32 Version: 4.8.4430.0 built by: NET48REL1LAST_B
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
> ## System.Numerics
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.3761.0 built by: NET48REL1
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
> ## System.Transactions
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.3761.0 built by: NET48REL1
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
> ## Microsoft.CSharp
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.3761.0
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
> ## Microsoft.Exchange.PowerShell.Configuration
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.PowerShell.Configuration.dll
> ## Microsoft.Exchange.Data.Directory
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.Directory.DLL
> ## Microsoft.Exchange.Diagnostics
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Diagnostics.DLL
> ## Microsoft.Exchange.Data
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.DLL
> ## Microsoft.Exchange.Net
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Net.DLL
> ## Microsoft.Exchange.Common
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Common.DLL
> ## Microsoft.Exchange.Data.Common
> Assembly Version: 15.1.2503.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Exchange.Data.Common/v4.0_15.1.2503.0__31bf3856ad364e35/Microsoft.Exchange.Data.Common.dll
> ## SMDiagnostics
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4261.0 built by: NET48REL1LAST_B
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
> ## System.ServiceModel.Internals
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4261.0 built by: NET48REL1LAST_B
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
> ## System.Web
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4330.0 built by: NET48REL1LAST_B
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
> ## Microsoft.Exchange.Management.Transport
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.Transport.DLL
> ## Microsoft.Exchange.Configuration.ObjectModel
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Configuration.ObjectModel.DLL
> ## Microsoft.Exchange.Management.Recipient
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.Recipient.DLL
> ## Microsoft.Exchange.Management
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.DLL
> ## Microsoft.Exchange.Data.Transport
> Assembly Version: 15.1.2503.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Exchange.Data.Transport/v4.0_15.1.2503.0__31bf3856ad364e35/Microsoft.Exchange.Data.Transport.dll
> ## Microsoft.Exchange.Transport.Logging.Search
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Transport.Logging.Search.DLL
> ## Microsoft.Exchange.Management.Powershell.Support
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.Powershell.Support.DLL
> ## Microsoft.Exchange.Rules.Common
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Rules.Common.DLL
> ## Microsoft.Exchange.MessagingPolicies.Rules
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.MessagingPolicies.Rules.DLL
> ## Microsoft.Exchange.Transport.Agent.InterceptorAgent
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Transport.Agent.InterceptorAgent.DLL
> ## Microsoft.Exchange.Transport.Agent.AntiSpam.Common
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Transport.Agent.AntiSpam.Common.DLL
> ## Microsoft.Exchange.Management.Provisioning
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.Provisioning.DLL
> ## Microsoft.Exchange.MessageSecurity
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.MessageSecurity.DLL
> ## Microsoft.Exchange.StoreProvider
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.StoreProvider.DLL
> ## Microsoft.Exchange.Management.Mobility
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.Mobility.DLL
> ## Microsoft.Exchange.Data.Storage
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.Storage.DLL
> ## Microsoft.Exchange.Management.Migration
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.Migration.DLL
> ## Microsoft.Exchange.MailboxReplicationService.Common
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.MailboxReplicationService.Common.DLL
> ## Microsoft.Exchange.Migration
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Migration.DLL
> ## Microsoft.Exchange.Data.MailboxLoadBalance
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.MailboxLoadBalance.DLL
> ## Microsoft.Exchange.Data.Mapi
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.Mapi.DLL
> ## Microsoft.Exchange.Compliance.TaskDistributionCommon
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Compliance.TaskDistributionCommon.DLL
> ## Microsoft.Exchange.Data.ApplicationLogic
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.ApplicationLogic.DLL
> ## Microsoft.Office.CompliancePolicy.Platform
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Office.CompliancePolicy.Platform.DLL
> ## Microsoft.Exchange.Data.StoreObjects
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.StoreObjects.DLL
> ## Microsoft.Exchange.UM.UMCommon
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.UM.UMCommon.DLL
> ## Microsoft.Exchange.Transport.Sync.Common
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Transport.Sync.Common.DLL
> ## Microsoft.Exchange.Data.Providers
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.Providers.DLL
> ## System.Xml.Linq
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.3761.0 built by: NET48REL1
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
> ## Microsoft.Exchange.PswsClient
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.PswsClient.DLL
> ## Microsoft.Exchange.Management.CompliancePolicy
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.CompliancePolicy.DLL
> ## Microsoft.Exchange.Data.resources
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/uk/Microsoft.Exchange.Data.resources.DLL
> ## Microsoft.Exchange.Common.Directory.DirectoryVariantConfig
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Common.Directory.DirectoryVariantConfig.DLL
> ## Microsoft.Exchange.Data.Directory.resources
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/en/Microsoft.Exchange.Data.Directory.resources.DLL
> ## Microsoft.Exchange.Configuration.RedirectionModule
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Configuration.RedirectionModule.DLL
> ## Microsoft.Exchange.WorkloadManagement
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.WorkloadManagement.DLL
> ## Microsoft.Exchange.Sqm
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Sqm.DLL
> ## Microsoft.Exchange.Configuration.Core
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Configuration.Core.DLL
> ## Microsoft.Exchange.VariantConfiguration.ExCore
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.VariantConfiguration.ExCore.DLL
> ## Microsoft.Exchange.VariantConfiguration.Core
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.VariantConfiguration.Core.DLL
> ## Microsoft.Search.Platform.Parallax
> Assembly Version: 3.3.0.0
> Win32 Version: 3.3.4.0
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Search.Platform.Parallax.DLL
> ## Microsoft.Exchange.VariantConfiguration
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.VariantConfiguration.dll
> ## Google.Protobuf
> Assembly Version: 3.7.0.0
> Win32 Version: 3.7.0.0
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Google.Protobuf.DLL
> ## Microsoft.PowerShell.HostingTools
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.PowerShell.HostingTools.DLL
> ## Microsoft.Exchange.Configuration.ObjectModel.resources
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/en/Microsoft.Exchange.Configuration.ObjectModel.resources.DLL
> ## System.Runtime.Caching
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.3761.0
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Caching/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Caching.dll
> ## Microsoft.Exchange.Extensibility.Internal
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Extensibility.Internal.DLL
> ## Microsoft.Exchange.Transport.Flighting
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/Bin/Microsoft.Exchange.Transport.Flighting.dll
> ## Microsoft.Exchange.Common.ComponentConfig.Transport
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/Bin/Microsoft.Exchange.Common.ComponentConfig.Transport.DLL
> ## Microsoft.Exchange.Core.TimeZone
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Core.TimeZone.DLL
> ## Microsoft.Exchange.Compliance
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Compliance.DLL
> ## Microsoft.GeneratedCode
> Assembly Version: 1.0.0.0
> Win32 Version: 4.8.3761.0 built by: NET48REL1
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ## Microsoft.Exchange.Core.TimeZone.resources
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/en/Microsoft.Exchange.Core.TimeZone.resources.DLL
> ## System.DirectoryServices.Protocols
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.3761.0 built by: NET48REL1
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.DirectoryServices.Protocols/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.DirectoryServices.Protocols.dll
> ## Microsoft.Exchange.VariantConfiguration.GlobalSettings
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.VariantConfiguration.GlobalSettings.DLL
> ## Microsoft.Exchange.Data.resources
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/en/Microsoft.Exchange.Data.resources.DLL
> ## Microsoft.GeneratedCode
> Assembly Version: 1.0.0.0
> Win32 Version: 4.8.3761.0 built by: NET48REL1
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ## Microsoft.Exchange.Transport.Extensibility
> Assembly Version: 15.0.0.0
> Win32 Version: 15.01.2507.006
> CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Transport.Extensibility.DLL
> ************** JIT Debugging ************** To enable just-in-time (JIT) debugging, the .config file for this application or computer (machine.config) must have the jitDebugging value set in the system.windows.forms section. The application must also be compiled with debugging enabled.
> 
> For example:
> 
> When JIT debugging is enabled, any unhandled exception will be sent to the JIT debugger registered on the computer rather than be handled by this dialog box.

Does BouncyCastle.Crypto.dll exist in the program directory?

**Comment by theklap** [comment]
I get the same error about BouncyCastle.Crypto.dll.
BouncyCastle.Crypto.dll exist in the directory and shows to be version 1.8.15362.1, while the error shows its looking for Version=1.9.0.0.

**Comment by DJBenson** [comment]
The version in the release package is 1.9.0.1;

![image](https://user-images.githubusercontent.com/1013909/170257239-c37f8ab6-d923-4924-aa86-33663a6ff4db.png)

Can you check your local version.

**Comment by theklap** [comment]
I ran the upgrade from inside the GUI and it seems to not update correctly, wrong .dll version.  Downloading the zip from the release page contains the correct .dll version.  Is there a process to upgrade from zip that we need to follow?

**Comment by YevgeniyN** [comment]
DLL version is 1.8.10.1
![image](https://user-images.githubusercontent.com/2317470/170260899-58f2f920-5f6f-4e1f-a03c-d8a423335322.png)


I also got couple of new DLLs with after upgrade to 3.4.1:
System.Memory.dll
System.Numerics.Vectors.dll
System.Runtime.CompilerServices.Unsafe.dll
System.Text.Encoding.CodePages.dll

**Comment by DJBenson** [comment]
Guys I'm stuggling with this one. I would stick with 3.4.0 until this issue is resolved - although there's an error in the event viewer, it doesn't appear to be causing an issue whereas my attempts to fix it have caused a further issue.

If anybody would like to take a look at the dependency issue with bouncycastle that would be appreciated.

**Comment by DJBenson** [comment]
Yes, sorry. Reopened.

v3.4.0 is the recommended version until this issue is resolved. I am struggling with the BouncyCastle dependency as no matter what I do the 1.8 version is bundled with the application and it needs 1.9. If anybody can assist please submit a PR.
